baseURL = 'https://fd.tllester.info/'
languageCode = 'en-us'
title = 'freeDimensional'

[params]
  description = 'a hybrid consultancy and volunteer network supporting artists on the frontlines of social change'
  logo = 'fd-crf-asn.png'

[menus]
  [[menus.main]]
    identifier = 'freedimensional'
    name = 'FreeDimensional'
    url = '/'
    weight = 10
  [[menus.main]]
    identifier = 'creativeresistancefund'
    name = 'Creative Resistance Fund'
    url = 'creativeresistancefund/'
    weight = 20
  [[menus.main]]
    identifier = 'artistsafety'
    name = 'ArtistSafety.net'
    url = 'artistsafety/'
    weight = 30
    # [[menus.main]]
    # identifier = 'Search'
    # name = 'Search'
    # url = 'search/'
    # weight = 40

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"